// src/components/CreateLobby/index.tsx
import { getSnapshot } from 'mobx-state-tree';
import React, { FC } from 'react';
import { Field, Form } from 'react-final-form';
import useWebsocketServer from '../../shared/hooks/websocketServer';
import { AppHeader } from '../../shared/StyledComponents/Headers';
import LobbyStore from '../../stores/lobby';
import { GameStatus, IProps } from '../App/types';
import { convertFormDataToModel, onValidate } from './helpersFns';
import { BlockSpacing, FloatingInput, FormFloating } from './styledComponents';
import { FormInputData } from './types';

const CreateLobby: FC<IProps> = ({ handleChangeGameStatus } : IProps) => {
  const publishLobby = useWebsocketServer('newLobby');

  const store = LobbyStore.create({
    lobbyName: '',
  });

  const backToMainPage = () => {
    handleChangeGameStatus(GameStatus.MAIN, null);
  };

  const handleSubmit = (values: FormInputData) => {
    const lobbyStore = LobbyStore.create(convertFormDataToModel(values));
    publishLobby(getSnapshot(lobbyStore));
    handleChangeGameStatus(GameStatus.WAIT_CONNECT, lobbyStore);
  };

  return (
    <Form
      initialValues={getSnapshot(store)}
      onSubmit={handleSubmit}
      validate={onValidate}
      render={((props) => (
        <>
          <AppHeader>New Lobby</AppHeader>

          <BlockSpacing>
            <Field name="lobbyName">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput
                    {...input}
                    className={(meta.error && meta.touched && 'is-invalid') as string}
                    type="text"
                    autoFocus
                  />
                  <label>{(meta.error && meta.touched) ? meta.error : 'Lobby Name'}</label>
                </FormFloating>
              )}
            </Field>
          </BlockSpacing>

          <BlockSpacing className="d-flex justify-content-between">
            <Field name="x">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput
                    type="number"
                    className={(meta.error && meta.touched && 'is-invalid') as string}
                    {...input}
                  />
                  <label>{(meta.error && meta.touched) ? meta.error : 'Field size: X'}</label>
                </FormFloating>
              )}
            </Field>
            <Field name="y">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput
                    type="number"
                    className={(meta.error && meta.touched && 'is-invalid') as string}
                    {...input}
                  />
                  <label>{(meta.error && meta.touched) ? meta.error : 'Field size: Y'}</label>
                </FormFloating>
              )}
            </Field>
          </BlockSpacing>

          <BlockSpacing className="d-flex justify-content-between">
            <Field name="ships4n">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput
                    className={(meta.error && 'is-invalid') as string}
                    type="number"
                    {...input}
                  />
                  <label>{(meta.error) ? meta.error : '4x ships count'}</label>
                </FormFloating>
              )}
            </Field>

            <Field name="ships3n">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput className={(meta.error && 'is-invalid') as string} type="number" {...input} />
                  <label>{(meta.error) ? meta.error : '3x ships count'}</label>
                </FormFloating>
              )}
            </Field>
          </BlockSpacing>

          <BlockSpacing className="d-flex justify-content-between">
            <Field name="ships2n">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput className={(meta.error && 'is-invalid') as string} type="number" {...input} />
                  <label>{(meta.error) ? meta.error : '2x ships count'}</label>
                </FormFloating>
              )}
            </Field>

            <Field name="ships1n">
              {({ input, meta }) => (
                <FormFloating>
                  <FloatingInput className={(meta.error && 'is-invalid') as string} type="number" {...input} />
                  <label>{(meta.error) ? meta.error : '1x ships count'}</label>
                </FormFloating>
              )}
            </Field>
          </BlockSpacing>

          <BlockSpacing className="d-flex justify-content-evenly">
            <button className="btn btn-secondary" onClick={backToMainPage}>Back</button>
            <button className="btn btn-primary" onClick={props.handleSubmit}>Create lobby</button>
          </BlockSpacing>
        </>
      ))}
    />
  );
};

export default CreateLobby;

// src/components/CreateLobby/CreateLobby.svelte
<script lang="ts">
import { getContext } from "svelte";
import createFieldValidator from "../../shared/helpers/validation";
import { requiredValidator,validateFieldSize,validateShipsCount } from "../../shared/helpers/validators";
import useWebsocketServer from "../../shared/hooks/websocketServer";
import Header from "../../shared/StyledComponents/Header.svelte";
import type { IStore } from "../../stores";
import { STORE_CONTEXT } from "../../stores";
import { LobbyStoreCreate } from "../../stores/lobby";
import { GameStatus } from "../App/types";

const mainStore = getContext<IStore>(STORE_CONTEXT).mainStore;
const publishLobby = useWebsocketServer('newLobby');

let formData = {
  name: '',
  x: 10,
  y: 10,
  ships4n: 1,
  ships3n: 2,
  ships2n: 3,
  ships1n: 4,
}

type TFormData = typeof formData; 

const { data: dataName, validate: validateName } = createFieldValidator<string>(requiredValidator<string>());
const { data: dataShips, validate: validateShips } = createFieldValidator<TFormData>(validateShipsCount<TFormData>());
const { data: dataFieldX, validate: validateFieldX } = createFieldValidator<number>(validateFieldSize<number>());
const { data: dataFieldY, validate: validateFieldY } = createFieldValidator<number>(validateFieldSize<number>());

const createLobby = () => {
  console.log(publishLobby);
  publishLobby(formData);

  mainStore.setLobby(
    GameStatus.WAIT_CONNECT, 
    LobbyStoreCreate(formData),
  );
}

const backToMainMenu = () => {
  mainStore.setGameStatus(GameStatus.MAIN);
}

</script>

<form>
  <Header>New Lobby</Header>

  <div class="spacing">
    <div class="form-floating">
      <input 
        autofocus
        bind:value={formData.name} 
        use:validateName={formData.name}
        class:is-invalid={$dataName.touch && !$dataName.valid}
        type="text" 
        class="form-control " 
      />
      <label>Lobby Name</label>
    </div>
  </div>

  <div class="spacing d-flex justify-content-between">
    <div class="form-floating">
      <input 
        bind:value={formData.x} 
        use:validateFieldX={formData.x}
        class:is-invalid={$dataFieldX.touch && !$dataFieldX.valid}
        type="number" 
        class="form-control" 
      />
      <label>Field size: X</label>
    </div>
    
    <div class="form-floating">
      <input 
        bind:value={formData.y} 
        use:validateFieldY={formData.y}
        class:is-invalid={$dataFieldY.touch && !$dataFieldY.valid}
        type="number" 
        class="form-control" 
      />
      <label>Field size: Y</label>
    </div>
  </div>


  <div class="spacing d-flex justify-content-between">
    <div class="form-floating">
      <input 
        bind:value={formData.ships4n} 
        use:validateShips={formData}
        class:is-invalid={!$dataShips.valid}
        type="number" 
        class="form-control"
      />
      <label>{$dataShips.message || "4x ships count"}</label>
    </div>
    
    <div class="form-floating">
      <input 
        bind:value={formData.ships3n} 
        use:validateShips={formData}
        class:is-invalid={!$dataShips.valid}
        type="number" 
        class="form-control"
      />
      <label>{$dataShips.message || "3x ships count"}</label>
    </div>
  </div>


  <div class="spacing d-flex justify-content-between">
    <div class="form-floating">
      <input 
        bind:value={formData.ships2n} 
        use:validateShips={formData}
        class:is-invalid={!$dataShips.valid}
        type="number" 
        class="form-control"
      />
      <label>{$dataShips.message || "2x ships count"}</label>
    </div>
    
    <div class="form-floating">
      <input 
        bind:value={formData.ships1n} 
        use:validateShips={formData}
        class:is-invalid={!$dataShips.valid}
        type="number" 
        class="form-control"
      />
      <label>{$dataShips.message || "1x ships count"}</label>
    </div>
  </div>

  <div class="spacing d-flex justify-content-evenly">
    <button on:click={backToMainMenu} type="button" class="btn btn-secondary">Back</button>
    <button 
      on:click={createLobby}
      disabled={!$dataName.valid || !$dataShips.valid || !$dataFieldX.valid || !$dataFieldY.valid }
      type="button" 
      class="btn btn-primary" 
    >Create lobby</button>
  </div>
</form>

<style>
  .spacing {
    padding: 10px 0;
  }
</style>
