// src/components/App/App.svelte
<script lang="ts">
import { getContext } from 'svelte';
import type { IStore } from '../../stores';
import { STORE_CONTEXT } from '../../stores';
import CreateLobby from '../CreateLobby/CreateLobby.svelte';
import LobbyList from '../LobbyList/LobbyList.svelte';
import MainPage from '../MainPage/MainPage.svelte';
import SetShips from '../SetShips/SetShips.svelte';
import WaitConnect from '../WaitConnect/WaitConnect.svelte';
import { GameStatus } from './types';

const mainStore = getContext<IStore>(STORE_CONTEXT).mainStore;
let store = mainStore.store;

const handleAcceptError = () => {
  mainStore.setError('');
}

</script>

<div>
  {#if $store.error}
    <div class="alertError alert alert-warning alert-dismissible fade show">
      <strong>{$store.error}</strong>
      <input type="button" class="btn-close" onClick={handleAcceptError} />
    </div>
  {/if}
  <div class="centerDiv">
    {#if $store.status === GameStatus.MAIN}
      <MainPage />
    {:else if $store.status === GameStatus.CREATE_LOBBY}
      <CreateLobby />
    {:else if $store.status === GameStatus.WAIT_CONNECT}
      <WaitConnect />
    {:else if $store.status === GameStatus.LOBBY_LIST}
      <LobbyList />
    {:else if $store.status === GameStatus.SET_SHIPS}
      <SetShips />
    {/if}
  </div>
</div>

<style>
.centerDiv {
  width: 600px;
  margin: 0 auto;
  text-align: center;
}

.alertError {
  text-align: center;
}
</style>

// src/components/App/index.tsx
import { inject, observer } from 'mobx-react';
import React, { FC } from 'react';
import { ILobbyStore } from '../../stores/lobby';
import { IMainStore } from '../../stores/mainStore';
import CreateLobby from '../CreateLobby';
import EndGameScreen from '../EndGameScreen';
import Game from '../Game';
import LobbyList from '../LobbyList';
import Main from '../MainPage';
import SetShips from '../SetShips';
import WaitConnect from '../WaitConnect';
import useWebsocketAppReconnect from './hooks';
import { AlertError, CenteredDiv } from './styledComponents';
import { GameStatus } from './types';

interface IAppProps {
  mainStore?: IMainStore
}

const App: FC<IAppProps> = inject('mainStore')(observer((props) => {
  const state = props.mainStore as IMainStore;

  useWebsocketAppReconnect(state);

  const handleGameStart = (startGame: GameStatus) => state?.setGameStatus(startGame);
  const handleSetLobby = (startGame: GameStatus, lobby: ILobbyStore) => state?.setLobby(startGame, lobby);
  const handleWaitLobby = (
    startGame: GameStatus,
    lobby: ILobbyStore | null = null,
  ) => state.setLobby(startGame, lobby);

  const handleAcceptError = () => state?.setError('');

  let component = null;

  switch (state.status) {
    case GameStatus.MAIN:
      component = (<Main handleChangeGameStatus={handleGameStart} />);
      break;

    case GameStatus.CREATE_LOBBY:
      component = (<CreateLobby handleChangeGameStatus={handleWaitLobby} />);
      break;

    case GameStatus.WAIT_CONNECT:
      component = (<WaitConnect />);
      break;

    case GameStatus.LOBBY_LIST:
      component = (<LobbyList handleSetLobby={handleSetLobby} />);
      break;

    case GameStatus.SET_SHIPS:
      component = (<SetShips />); break;

    case GameStatus.GAME:
      component = (<Game />);
      break;

    case GameStatus.GAMEWIN:
    case GameStatus.GAMEOVER:
      component = (<EndGameScreen gameResult={state.status as GameStatus} />);
      break;

    default:
      break;
  }

  let err = null;

  if (state?.error) {
    err = (
      <AlertError>
        <strong>{state?.error}</strong>
        <input type="button" className="btn-close" onClick={handleAcceptError} />
      </AlertError>
    );
  }

  return (
    <>
      {err}
      <CenteredDiv>
        {component}
      </CenteredDiv>
    </>
  );
}));

export default App;
