// src/components/SetShips/SelectShipsPosition.svelte
<script lang="ts">
import ShipElement from "./ShipElement.svelte";



type TDecraseShip = (n: number) => void;

export let ships4n: number; 
export let ships3n: number;
export let ships2n: number;
export let ships1n: number;
export let decraseShip: TDecraseShip;

</script>

<div class="block-padding">
  <div class="block-element d-flex">
    <ShipElement shipSize={4} disabled={!ships4n} />
    <span>
      {' '}
      x
      {ships4n}
    </span>
  </div>

  <div class="block-element d-flex">
    <ShipElement shipSize={3} disabled={!ships3n} />
    <span>
      {' '}
      x
      {ships3n}
    </span>
  </div>

  <div class="block-element d-flex">
    <ShipElement shipSize={2} disabled={!ships2n} />
    <span>
      {' '}
      x
      {ships2n}
    </span>
  </div>

  <div class="block-element d-flex">
    <ShipElement shipSize={1} disabled={!ships1n} />
    <span>
      {' '}
      x
      {ships1n}
    </span>
  </div>
</div>

<style lang="scss">
  .block-padding {
    padding-left: 25px;
  }

  .block-element {
    padding: 10px 0;

    & span {
      padding-left: 10px;
    }
  }
</style>

// src/components/SetShips/Field/SelectShipsPosition.tsx
import { observer } from 'mobx-react';
import React, { FC } from 'react';
import { ShipBlockElement, ShipBlockPadding } from '../styledComponents';
import ShipElement from './ShipElement';

interface IProp {
  ships4n: number,
  ships3n: number,
  ships2n: number,
  ships1n: number,
  decraseShip: (shipSize: number) => void
}

const SelectShipsPosition: FC<IProp> = observer((props: React.PropsWithChildren<IProp>) => {
  const {
    ships4n, ships3n, ships2n, ships1n, decraseShip,
  } = props;

  return (
    <>
      <ShipBlockPadding>
        <ShipBlockElement>
          <ShipElement shipSize={4} disabled={!ships4n} onDragComplete={() => decraseShip(4)} />
          <span>
            {' '}
            x
            {ships4n}
          </span>
        </ShipBlockElement>
        <ShipBlockElement>
          <ShipElement shipSize={3} disabled={!ships3n} onDragComplete={() => decraseShip(3)} />
          <span>
            {' '}
            x
            {ships3n}
          </span>
        </ShipBlockElement>
        <ShipBlockElement>
          <ShipElement shipSize={2} disabled={!ships2n} onDragComplete={() => decraseShip(2)} />
          <span>
            {' '}
            x
            {ships2n}
          </span>
        </ShipBlockElement>
        <ShipBlockElement>
          <ShipElement shipSize={1} disabled={!ships1n} onDragComplete={() => decraseShip(1)} />
          <span>
            {' '}
            x
            {ships1n}
          </span>
        </ShipBlockElement>

        {props.children}
      </ShipBlockPadding>
    </>
  );
});

export default SelectShipsPosition;
