// src/components/LobbyList/LobbyList.svelte
<script lang="ts">
import { getContext, onMount } from "svelte";
import { STORE_CONTEXT } from "../../stores";
import useWebsocketServer from "../../shared/hooks/websocketServer";
import Header from "../../shared/StyledComponents/Header.svelte";
import { GameStatus } from "../App/types";
import { get} from "svelte/store";
import type { IStore } from "../../stores";
import type { ILobbySet, ILobbyData } from "../../stores/lobbyList";
import type { ILobby } from "../../stores/lobby";
import type { Readable }   from "svelte/store";

const {
  lobbyList,
  mainStore,
} = getContext<IStore>(STORE_CONTEXT);
const lobbyListStore = lobbyList.store;

const connectToLobby = useWebsocketServer('connectLobby');

const lobbyListRequest = useWebsocketServer('lobbyList', (data: ILobbyData) => {
  lobbyList.updateFromServer(data);
});

onMount(() => {
  lobbyListRequest({});
})

interface ILobbyArrayItem {
  userId: string,
  data: ILobby,
  lobby: Readable<ILobby>,
}

let lobbyListData: ILobbyArrayItem[] = [];

$: {
  lobbyListData = Object.entries($lobbyListStore).map((items) => {
    const [userId, lobby] = items;

    return {
      userId: userId,
      data: get(lobby),
      lobby: lobby,
    };
  });
}

const handleJoin = (user: string, lobby: Readable<ILobby>) => {
  connectToLobby(user);
  mainStore.setLobby(GameStatus.SET_SHIPS, lobby);
  console.log('Joined')
};

</script>

<Header>Lobby list</Header>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <td />
      <td>Lobby name</td>
      <td>Field size</td>
      <td>Ships 4x/3x/2x/1x</td>
    </tr>
  </thead>
  <tbody>
    {#each lobbyListData as lobbyItem}
      <tr>
        <td>
          <button class="btn btn-secondary" on:click={() => handleJoin(lobbyItem.userId, lobbyItem.lobby)}>Join</button>
        </td>
        <td>{lobbyItem.data.name}</td>
        <td>
          {lobbyItem.data.x} x {lobbyItem.data.y}
        </td>
        <td>
          {lobbyItem.data.ships4n} / {lobbyItem.data.ships3n} / {lobbyItem.data.ships2n} / {lobbyItem.data.ships1n}
        </td>
      </tr>
    {/each}
  </tbody>
</table>

// src/components/LobbyList/index.tsx
import { inject, observer } from 'mobx-react';
import React, { FC, useEffect } from 'react';
import useWebsocketServer from '../../shared/hooks/websocketServer';
import { AppHeader } from '../../shared/StyledComponents/Headers';
import { IDataFromServer, ILobbyStore } from '../../stores/lobby';
import { ILobbyList } from '../../stores/lobbyList';
import { GameStatus, ISetLobbyProps } from '../App/types';
import { LobbyTable } from './styledComponents';

interface IProps extends ISetLobbyProps {
  lobbyList?: ILobbyList
}

const LobbyList: FC<IProps> = inject('lobbyList')(observer((props: IProps) => {
  const lobbyList = props.lobbyList as ILobbyList;
  const { handleSetLobby } = props;
  const connectToLobby = useWebsocketServer('connectLobby');

  const lobbyListRequest = useWebsocketServer('lobbyList', (data: IDataFromServer) => {
    lobbyList.updateFromServer(data);
  });

  useEffect(() => {
    lobbyListRequest({});
  }, [lobbyListRequest]);

  const handleJoin = (user: string, lobby: ILobbyStore) => {
    connectToLobby(user);
    handleSetLobby(
      GameStatus.SET_SHIPS,
      lobby,
    );
  };

  const items: JSX.Element[] = [];
  for (const record of lobbyList?.lobbys.values()) {
    items.push(
      <tr key={record.name}>
        <td>
          <button className="btn btn-secondary" onClick={() => handleJoin(record.name, record.value)}>Join</button>
        </td>
        <td>{record.value.lobbyName}</td>
        <td>
          {record.value.x}
          x
          {record.value.y}
        </td>
        <td>
          {record.value.ships4n}
          /
          {record.value.ships3n}
          /
          {record.value.ships2n}
          /
          {record.value.ships1n}
        </td>
      </tr>,
    );
  }

  return (
    <>
      <AppHeader>Lobby list</AppHeader>
      <LobbyTable>
        <thead>
          <tr>
            <td />
            <td>Lobby name</td>
            <td>Field size</td>
            <td>Ships 4x/3x/2x/1x</td>
          </tr>
        </thead>
        <tbody>
          {items}
        </tbody>

      </LobbyTable>
    </>
  );
}));

export default LobbyList;
